# Generated by Django 5.1.6 on 2025-03-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descripction',
            new_name='description',
        ),
    ]
